require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - 'config/**/**'
    - 'bin/**/**'
    - 'lib/**/**'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
