require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.2
  Exclude:
    - 'config/**/**'
    - 'bin/**/**'
    - 'lib/**/**'
    - 'vendor/**/**'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'db/schema.rb'

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/NestedGroups:
  Max: 3

Style/HashSyntax:
  EnforcedShorthandSyntax: 'never'

Lint/MissingSuper:
  Enabled: false
