name: Lint and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  RUBY_VERSION: 3.1.2
  NODE_VERSION: 16.17.1

jobs:
  lint:
    name: Lint and audit code
    runs-on: ubuntu-20.04
    steps:
     - name: Checkout code
        uses: actions/checkout@v3
        
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{env.RUBY_VERSION}}
          bundler-cache: true

      - name: Prepare ENV
        run: |
          sudo apt-get update
          sudo apt-get install libvips42=8.9.1-2
      - name: Run Bundler check and audit
        run: bundle exec bundle-audit check --update

      - name: Run Zeitwerk check
        run: bundle exec rails zeitwerk:check

      - name: Run Rubocop
        run: bundle exec rubocop
